### ISSUE TITLE
Unexpected Token when importing with assert { type: 'css' };

### ISSUE THREAD

**Issue by walterjj** [jleeson/rollup-plugin-import-css#10]
When running directly from the sources , JavaScript needs the " assert {type:'css'}" modifier, otherwise you get this error at run time:

![image](https://user-images.githubusercontent.com/1050091/222445376-818bca5d-7d72-4ef4-ac11-4335ab6a3337.png)

But if I try to build,  stops with "unexpected token". 
The workaround is comment  the offending attribute for building: like this:

![image](https://user-images.githubusercontent.com/1050091/222444594-63fcf3be-6632-483c-8506-5a392a9eeab0.png)

**Comment by walterjj** [comment]
Hi Jacob! , Yes,  I run the code directly in the browser and  through rollup,  just becouse I like to write code that can work as native modules.. Thats why a time ago I begun with web components in the first place. 

But after I' d create the issue  I'v got aware of  that  difference!
The browser don't let me to import the css file as a string without the import assertion ( or may be I don´t know how to do it )
and  the rollup plugin doesn't like the assertion...

What I am doing now i to comment the import assertion when building thought rollup,  and  detecting the case with try/catch in the code  to detect CSSStyleSheet or string:

```
 try {
      this.shadowRoot.adoptedStyleSheets.push(sheet); 
  }
  catch(e){
      const styleSheet = new CSSStyleSheet();
      styleSheet.replace(css);
      this.shadowRoot.adoptedStyleSheets.push(styleSheet);
  }
 ```
 
 So, it's not a bug of the plugin,  but it it an issue-- May be a  configuration option to simply ignore the assertion? 
 
 Thankyou!

**Comment by jleeson** [comment]
I 100% agree with you on this. The plugin is lacking the functionality to support the assert syntax. Rather than enable this through a config option for the plugin, I think the best way to handle it is change the plugin functionality when it encounters the assert syntax. That way this plugin can be used to just enable the standard syntax in rollup.

Currently there are two "modes" of importing css with this plugin, Mode 3 can be automatically used when detecting the assert syntax and instead of it importing as a string, it will follow the standard and import it as a CSSStyleSheet.

**Mode 1 - import the css to be extracted to a css bundle**
```js
import "./styles.css";
```

**Mode 2 - import the css as a string**
```js
import styles from "./styles.css";
```

**Mode 3 - import the css as a CSSStyleSheet**
```js
import stylesheet from "./styles.css" assert { type: "css" };
```

Would this solve your problem and enable you to run the code with and without rollup?
If so I can begin work on this over the weekend.

**Comment by walterjj** [comment]
Of course it would solve the problem ,and  that's the best solution I think!! 

Thankyou for your work !!

**Comment by jleeson** [comment]
Awesome, ill update here when I have this feature released hopefully this weekend. Should enable you to just use the import assertions and remove your try and catch all together.

**Comment by jleeson** [comment]
Hey @walterjj, I was able to add the new feature and release it today. Make sure you update this plugin to v3.2.0 and make sure you are using Rollup v3+, Rollup v2 does not have the capability to parse import assertion syntax and will throw an "unexpected token" error. Once you have updated to Rollup v3 and rollup-plugin-import-css v3.2.0 your import assertions should automatically work and in rollup it will import them as a CSSStyleSheet as defined in the spec. I have also added a `modules` option which will import the css as a CSSStyleSheet without the assertion syntax in order to enable this functionality on Rollup v2.

Give it a try and let me know if it resolves your issue.

**Comment by walterjj** [comment]
Hi @jleeson.. We are better: Now the import assertion is accepted but the imported value seems to be undefined: 

```
import sheet from 'xterm/css/xterm.css'  assert { type: 'css' };
...
...
firstUpdated() {
    try {
      this.shadowRoot.adoptedStyleSheets.push(sheet); 
      console.log("adoptedStyleSheets works",sheet);
    }
    catch(e){
      console.log("adoptedStyleSheets didn't work",sheet);
      .........
    }
```
results in:
```
adoptedStyleSheets didn't work undefined
```

**Comment by walterjj** [comment]
same result with {modules:true}  :
( rollup version is 3.18.0 , so I understand that "modules" option  is not needed, , but tryed anyway .

**Comment by jleeson** [comment]
thats odd, are you able to show what the compiled output is for the import? should be able to open the rollup bundle and do a search for `new CSSStyleSheet`

**Comment by walterjj** [comment]
I think the problem is at line 43:
```
code: `export default new CSSStyleSheet().replaceSync(${JSON.stringify(transformedCode)});`,
```
replaceSync return value is undefined  https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/replaceSync

**Comment by jleeson** [comment]
My bad, you are correct. This is corrected with v3.2.1. Please let me know if there are any further issues.

**Comment by walterjj** [comment]
It works perfectly now!!  the problem is solved. 
Thank you very much Jacob!! very good and very fast!

**Comment by jleeson** [comment]
Happy to help! If there is any other problems you run into feel free to open another issue.
