### ISSUE TITLE
CSS Not importing

### ISSUE THREAD

**Issue by Miniontoby** [jleeson/rollup-plugin-import-css#11]
Hi! 

I just added this plugin to my rollup config and it generates the bundle.css, but when I run my app, it doesn't include the css file.

I cannot make use of any type of code as seen below here:
```js
import styles from "./style.css";
const style = document.createElement('style');
style.textContent = styles;
document.head.appendChild(style);
```
That is because I am making a plugin for making apps and I cannot require people to remove/lower their CSP rules.

I hope you have got an idea.

- Miniontoby

**Comment by jleeson** [comment]
HI @Miniontoby, Can you share your rollup config? when you import the css as shown in the example you gave, it should not generate a css bundle at all and instead only import it as a string. When a css bundle is generated, the css bundle is emitted through rollup as an asset, it is not automatically included in your application unless you are also using a plugin such as `@rollup/plugin-html` that will detect the asset and include it.

Either way the css being imported as a string should be working, if you can share your rollup config and what config options your using for this plugin i can take a look.

**Comment by Miniontoby** [comment]
> HI @Miniontoby, Can you share your rollup config? when you import the css as shown in the example you gave, it should not generate a css bundle at all and instead only import it as a string. When a css bundle is generated, the css bundle is emitted through rollup as an asset, it is not automatically included in your application unless you are also using a plugin such as `@rollup/plugin-html` that will detect the asset and include it.
> 
> Either way the css being imported as a string should be working, if you can share your rollup config and what config options your using for this plugin i can take a look.

The code I showed, was to show how I could fix it. That solution DOES work, but I cannot put it into my code because it will violate CSP rules. 

The actual code I use rn is just `import './style.css';`

My rollup.config.js:
```js
import { nodeResolve } from '@rollup/plugin-node-resolve'
import { terser } from 'rollup-plugin-terser'
import typescript from '@rollup/plugin-typescript'
import css from "rollup-plugin-import-css";

export default {
  input: './webview-src/index.ts',
  output: {
    dir: './webview-dist',
    entryFileNames: '[name].js',
    format: 'es',
    exports: 'auto'
  },
  plugins: [
    nodeResolve(),
    terser(),
    typescript({
      tsconfig: './webview-src/tsconfig.json',
      moduleResolution: 'node'
    }),
    css()
  ]
}
```

So I think it might just be because I don't have anything that includes it yeah... But I don't want to force/require users to add the css manually, cause that just isn't ideal, so if my code could import it by itself it would be nice!

**Comment by jleeson** [comment]
Ok so it looks like this plugin is functioning exactly as intended. the only way to have the css be imported into your code without extracting it to a bundle is to import it as a string or as of v3.2 import it as a CSSStyleSheet. Im not sure how you are planning to use your code but the only way for the css bundle to be automatically included in the app is if you are also generating the html. 

Does importing the css as a string and adding it to the document body work without violating CSP? if not would using `document.adopedStyleSheets` work? (using v3.2 and enable the modules option on this plugin)

Ex:
```js
import stylesheet from "./styles.css";
document.adoptedStyleSheets = [stylesheet];
```

If your able to share a little more context on how your users will use your code I can try to offer better suggestions, but atm css cant be included without importing it as a variable or generating the html yourself via another plugin.

**Comment by Miniontoby** [comment]
Uhmm, using that code it gives me this error: 

`Uncaught TypeError: Failed to set the 'adoptedStyleSheets' property on 'Document': Failed to convert value to 'CSSStyleSheet'.`

Look, I know out of experience that CSP will block inline styles (like inside `<style>` tags), it wants you to have it inside a file.
Same for event listeners, these have to be inside javascript assigned, but thats not important here now.

But yeah what my plugin does is actually provide an API which wasn't available and then also add a modal to select some stuff. And for that modal I need css, cause else it doesn't look good.

**Comment by jleeson** [comment]
for use with adoptedStyleSheets you need to be using native css modules. this feature was released 2 days ago so you would need to make sure you have the latest version of this plugin installed and either use import assertions or enable the modules option. That should remove the error you are seeing.

To resolve the error you must be using rollup v3 and rollup-plugin-import-css v3.2.1.

What is your plugin for? knowing the context the code needs to be used in will help me determine the best way to automatically include the styles. I suggested the use of a style tag because in most cases you can use a style tag to embed styles. This is how most rollup plugins will handle injecting css. Is your plugin a browser extension, is it meant to be used with wordpress? where does it get used? once i know the limitations of the environment I can try to help further.

This plugin is functioning correctly so there is nothing I can fix in this plugin to resolve the issue and if you cant inject a style tag the only other options i can currently think of is to either manually add the css file which as you said is not ideal or if the environment supports constructible style sheets, using the document.adoptedStyleSheets api.

**Comment by jleeson** [comment]
When using adoptedStyleSheets here is an example of what you need to do to enable it.

Required: `rollup@3, rollup-plugin-import-css@3.2.1`

**rollup config**
```js
import css from "rollup-plugin-import-css";

export default {
    input: "index.js",
    output: { file: "dist/index.js", format: "esm" },
    plugins: [ css({ modules: true }) ]
};
```

You can then use native css module syntax with assert or you can use the `modules: true` option in the config.

```js
/* use native modules */
import styles from "./styles.css" assert { type: "css" };

/* use the modules option in rollup-plugin-import-css */
import styles from "./styles.css";

/* add the stylesheet to the document */
document.adoptedStyleSheets = [styles];
```

Hopefully this method will work for you since its not using a css bundle and its not using a style element.

**Comment by Miniontoby** [comment]
```
import { nodeResolve } from '@rollup/plugin-node-resolve'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:834:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:409:24)
    ```

**Comment by Miniontoby** [comment]
Just adding in the `modules: true` does allow the `import styles from "./styles.css";` to work with the adoptedStyleSheets

**Comment by jleeson** [comment]
Glad you were able to use adoptedStyleSheets to solve it.
