### ISSUE TITLE
How to generate only one file bundle.css instead of generating new unique file every time I save changes

### ISSUE THREAD

**Issue by markstopkidding** [jleeson/rollup-plugin-import-css#15]
Hello! I'm new in programming and now I am building my second project on JS. I am using this plugin to bundle my css files, but when I save changes, this plugin makes new folder called "assets" and put there file like "bundle-ea06de58.css". After next saving changes it makes new file like "bundle-aeb0df5f.css" in folder "assets". I want this plugin to generate only one file "bundle.css" in folder "dist" and  regenerate it after every saving without creating new unique files. I saw that this plugin has options, but I can not understand how to use them. How can I solve my problem?

**Comment by jleeson** [comment]
Hi @markstopkidding, I hope your enjoying programming so far!

In order to change how the css bundle is created you can use the options provided by the plugin, the behavior and data types of the options are outlined in the readme. Since you would like your css bundle file to be called "bundle.css" and have it always generated inside the "dist" folder, here is an example config that does this:

```js
import css from "rollup-plugin-import-css";

export default {
    input: "index.js",
    output: { file: "dist/index.js", format: "esm" },
    plugins: [ css({ output: "bundle.css" }) ]
};
```

the plugin determines the build folder using the rollup output.file option, in this case the folder is "dist", then in the css plugin options you can specify the output file name, this is where you can set the file name to "bundle.css".

this should create the outcome you are a looking for. I hope this helps. Let me know if you have any further questions.

**Comment by markstopkidding** [comment]
Thank you very much! Your answer helped me a lot!
