### ISSUE TITLE
How to declare module type for Typescript?

### ISSUE THREAD

**Issue by BoldyrevDA** [jleeson/rollup-plugin-import-css#19]
There are different ways to import css by [rollup-plugin-import-css](https://github.com/jleeson/rollup-plugin-import-css).

So, this way
```
import styles from "./styles.css"; /* import the styles as a string */
```
I described in `declaration.d.ts` as 

 ```
declare module "*.css" {
    const css: string;
    export default css;
}
```

But is there way to declare import with assertion?
```
import styles from "./styles.css" assert { type: "css" }; /* import the styles as a CSSStyleSheet */
```

**Comment by jleeson** [comment]
@BoldyrevDA Unfortunately it does not appear that TypeScript currently has a way to declare ambient declarations for import assertions. You can read more on that at microsoft/TypeScript#46135

However depending on your use for this plugin, you can change the import behavior of the string import to be a CSS Module rather than using assert syntax. In order to do this, add the `modules: true` option to the plugin config, and then you should be able to update your `declaration.d.ts` with the following:

```ts
declare module "*.css" {
   const stylesheet: CSSStyleSheet;
  export default stylesheet;
}
```

Its worth noting that when using `modules: true`, your css imports will be non-standard and importing styles as a string will not work anymore.

**Comment by jleeson** [comment]
Closing this since its a question regarding TypeScript syntax support.
